### ISSUE TITLE
Emacs formatting.

### ISSUE THREAD

**Issue by carlhu** [Engelberg/better-cond#17]
Strictly speaking, this is orthogonal to the better-cond library, but since better-cond is related to readability, solving this and including it in the readme might be warranted.

For `let` statements, many people prefer the clojure-mode vertically aligning the right expressions. Unfortunately, with better-cond, clojure-mode does not understand either the let and the :let forms. 

Do we have any solutions for this available yet?

**Comment by Engelberg** [comment]
I do use emacs, but don't have any knowledge of how to customize clojure-mode. I've always been satisfied with the :let formatting, but I don't know about the vertical alignment of the right expressions. I assume, like everything about emacs, there's some way to customize it, but I don't know exactly how. I'd suggest going to the cider channel of clojurians.slack.com, and asking the folks there.

**Comment by carlhu** [comment]
Thank you for reviewing this, Mark.
