### ISSUE TITLE
clj-kondo 'unresolved symbol' when using intermediary :let on when-let, if-let

### ISSUE THREAD

**Issue by bortexz** [Engelberg/better-cond#23]
As the title says, clj-kondo reports unresolved-symbols that are declared inside intermediary :let when using if-let, when-let (probably too on when-some, if-some)

```clojure

(if-let [a 1
         :let [b false]]
             ; ^ unresolved-symbol, here and any further use of b
  ...
  ...)

```

**Comment by Engelberg** [comment]
Thanks. I don't personally have any knowledge of clj-kondo; the pull request to support clj-kondo was provided by @borkdude. Probably the next step would be to create a pull request that adds test cases to better-cond which utilize the feature that clj-kondo is marking as an unresolved symbol. Then someone with clj-kondo expertise can take a look at the report generated by the branch with the new test cases, and figure out how to allow for that.

**Comment by borkdude** [comment]
I'd be happy to contribute that.

**Comment by Engelberg** [comment]
Thanks for reporting this, and thanks to @borkdude for the pull request to fix the issue. This has been deployed to clojars as version 2.1.5.

**Comment by bortexz** [comment]
Thank you both 🙏🏼
