### ISSUE TITLE
ClojureScript

### ISSUE THREAD

**Issue by madstap** [Engelberg/better-cond#7]
Would be nice if this was a cljc file. Is there some reason that it's not?

**Comment by Engelberg** [comment]
These are all macros.  Macros go in a clj file, not a cljc file.

It should work in Clojurescript as-is, but I have not tested it yet.  Could you give it a try and let me know?

**Comment by madstap** [comment]
I never really understood how macros and cljs interact, but I was expecting it to work, and when it didn't I just figured my understanding of it was flawed, and that it needs a cljs namespace.

It works in the clj files in my project, but in the cljs ones I get `No such namespace: better-cond.core, could not locate better_cond/core.cljs, better_cond/core.cljc, or Closure namespace "better-cond.core"`.

If I make a cljc file in my project and copy all the code from better cond, inside `#?(:clj )`, it works.

I'm having some pretty major tooling issues atm though, so that might be it. When I have some time tomorrow I'll try in a more minimal project without figwheel, cider and friends.

**Comment by Engelberg** [comment]
Did you use `:require-macros` in your namespace declaration?  That's the one thing I would expect to be different to use it from clojurescript.

**Comment by madstap** [comment]
I was under the impression that :require-macros was automatic now. It worked without it when I used a cljc file in my own project. My understanding is now that it is automatic if there's also a cljs namespace with the same name. It works now with :require-macros, and I feel dumb.

**Comment by Engelberg** [comment]
I think you're right that there have been some changes.  I'll try to figure out if there is something I can do to make it work with cljs' new auto-detect feature, but I'm pleased to know it currently works when doing it the old way with :require-macros.  Thanks for testing that out and reporting back.
