### ISSUE TITLE
`:when-some` support

### ISSUE THREAD

**Issue by cgrand** [Engelberg/better-cond#9]
Hi Mark, are you ok for a PR adding `:when-some`?

**Comment by Engelberg** [comment]
As in, whenever it is not nil?

Sure.  Sounds like a great idea.  

Please submit pull request for https://github.com/Engelberg/better-cond/tree/v2.0.1, which is tracking the 1.9 alpha release, and will become the main version as soon as 1.9 is officially released.

**Comment by cgrand** [comment]
> As in, whenever it is not nil?

Yes.

FYI here is the kind of `cond` I write these days:
```clj
(defmacro cond
  ([] nil)
  ([c e & etc]
    (case c
      :let `(let ~e (cond ~@etc))
      :when-let `(when-let ~e (cond ~@etc))
      :when-some `(when-some ~e (cond ~@etc))
      (case (and (vector? c) (some #{:let :some} (keys (meta c))))
        :let `(if-let ~(vary-meta c dissoc :let) ~e (cond ~@etc))
        :some `(if-some ~(vary-meta c dissoc :some) ~e (cond ~@etc))
        `(if ~c ~e (cond ~@etc))))))
```

I use `:let` or `:some` metadata on pairs in condition position to determine which kind of `if` to emit.

**Comment by Engelberg** [comment]
:when-some support added in version 2.0.2
